### GENERAL FILE STORAGE ###
DATA_DIR_PATH: "./data/"
JSON_INPUT_DIR_PATH: "./data/jsons/input/"
JSON_OUTPUT_DIR_PATH: "./data/jsons/output/"
NUMERICAL_DIR_PATH: "./data/numerical/"
OUTPUT_DIR_PATH: "./output/"
METADATA_DIR: "./data/meta/"

### EVAL ###
INPUT_ALL_DICT: "./data/jsons/input/processed_patient_dict.json"
INPUT_D1_DICT: "./data/jsons/input/tumor_normal_d1.json"
INPUT_D2_DICT: "./data/jsons/input/ggg_aggressiveness_d2.json"
GIBBS_ALL_HDF5: "./data/numerical/processed_data.h5"
GIBBS_ALL_JSON: "./data/jsons/output/processed_data.json"
GIBBS_D1_HDF5: "./data/numerical/tvn_d1.h5"
GIBBS_D1_JSON: "./data/jsons/output/tvn_d1.json"
GIBBS_D2_HDF5: "./data/numerical/ggg_d2.h5"
GIBBS_D2_JSON: "./data/jsons/output/ggg_d2.json"
EVAL_DIR_PATH: "./output/eval/"

### GIBBS ###
INPUT_DICT_PATH: "./data/jsons/input/tumor_normal_d1.json"
OUTPUT_HDF5_PATH: "./data/numerical/tvn_d1.h5"
OUTPUT_JSON_PATH: "./data/jsons/output/tvn_d1.json"
METADATA_PATH: "./data/meta/patient_gleason_grading.csv"
OUTPUT_PRINT_ROI_PATH: "./output/gibbs/"

### SIMULATION ###
SIM_PDF: "./output/testing/simulation_results.pdf"
SIM_CSV: "./output/testing/simulation_results.csv"
