# Configuration for Gradient Boosting Cancer Biomarker Classification
name: gradient_boosting
type: gradient_boosting

# Model hyperparameters
hyperparameters:
  # Boosting parameters
  n_estimators: 100
  learning_rate: 0.1

  # Tree parameters
  max_depth: 3
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: null # Use all features

  # Regularization
  subsample: 1.0 # Fraction of samples for each tree
  min_impurity_decrease: 0.0

  # Loss function
  loss: "log_loss" # For classification

  # Early stopping
  validation_fraction: 0.1
  n_iter_no_change: null # Disable early stopping by default
  tol: 1e-4

# Cross-validation settings
cross_validation:
  enabled: true
  n_folds: 5
  stratified: true
  random_state: 42

# Feature engineering
feature_engineering:
  include_spectrum_features: true
  include_adc_comparison: true
  include_clinical_metadata: true

  # Feature scaling
  scale_features: false # Not necessary for tree-based methods

  # Feature selection
  feature_selection:
    enabled: false
    method: "gradient_importance"
    importance_threshold: 0.01

# Target configuration
target:
  type: "binary"
  gleason_threshold: 7
  labels:
    low_grade: "GGG 1-3 (≤7)"
    high_grade: "GGG 4-5 (>7)"

# Evaluation metrics
evaluation:
  primary_metric: "auc"
  metrics:
    - "auc"
    - "accuracy"
    - "sensitivity"
    - "specificity"
    - "precision"
    - "f1_score"
    - "quadratic_weighted_kappa"

  bootstrap_ci: true
  n_bootstrap: 1000
  confidence_level: 0.95

# Interpretation
interpretation:
  feature_importance: true
  shap_analysis: false
  staged_score: true # Track performance over boosting rounds

# Visualization
visualization:
  confusion_matrix: true
  roc_curve: true
  feature_importance_plot: true
  calibration_plot: true
  learning_curve: true
