# Hydra config for the bwh dataset
name: bwh
true_spectrum_name: None
# Uniform multi-resolution discretization (8 bins, final version)
# Rationale: Uniform spacing within clinical ranges
#   - Tumor (D ≤ 1): Δ=0.25 → 4 bins for Gleason differentiation
#   - Normal (1 < D ≤ 2): Δ=0.5 → intermediate resolution
#   - High-D (2 < D ≤ 3): Δ=1.0 → coarse, less clinical relevance
#   - Free water (D=20): CSF/vascular at b=0
# Intervals (overlapping): [0,1]=4 values, [1,2]=3 values, [2,3]=2 values
# Condition number: κ = 2.78e5 (excellent for NUTS with ridge strength=0.5)
diff_values: [0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 20.0]
# B-values from BWH acquisition protocol (0-3500 s/mm²)
b_values:
  [0., 0.25, 0.5, 0.75, 1., 1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5]
signal_decays_json: ${hydra:runtime.cwd}/src/spectra_estimation_dmri/data/bwh/signal_decays.json
metadata_csv: ${hydra:runtime.cwd}/src/spectra_estimation_dmri/data/bwh/metadata.csv
# Subset sampling for testing (null = use all samples)
max_samples: null # Set to integer (e.g. 5) for quick testing

# Biomarker analysis configuration (automatic for BWH)
biomarker_n_mc_samples: 200 # Number of MC samples for uncertainty propagation
biomarker_regularization: 1.0 # L2 regularization strength for logistic regression
biomarker_adc_b_range: [0.0, 1.25] # ADC b-value range in ms units (0-1250 s/mm²)
