# Main Hydra configuration file
# Set up defaults for dataset

defaults:
  - dataset: simulated
  - likelihood: gaussian
  - prior: lasso
  - inference: map
  - classifier: logistic_regression
  - diagnostics: diagnostics
  - _self_

recompute: false
experiment_name: "spectra_estimation_test_1"
seed: 42
