# Main Hydra configuration file
# Set up defaults for dataset

defaults:
  - dataset: simulated
  - model: nonneg_gaussian
  - inference: map
  - classifier: logistic_regression
  - diagnostics: boxplot
  - _self_

experiment_name: "spectra_estimation_test_1"
seed: 42
