# Main Hydra configuration file
# Set up defaults for dataset

defaults:
  - dataset: simulated
  - model: nonneg_gaussian
  - inference: gibbs
  - classifier: logistic_regression
  - plot: boxplot
  - _self_

experiment_name: "spectra_estimation_test_1"
seed: 42

dataset:
  true_spectrum_name: normal_peripheral_zone
